// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJGPLdIRHq9fOu64zSiHf3TAwoCimVTgw',
    appId: '1:726365459693:web:8a3ae7cd21609b9619e8e4',
    messagingSenderId: '726365459693',
    projectId: 'flutter-prep-2f8a0',
    authDomain: 'flutter-prep-2f8a0.firebaseapp.com',
    storageBucket: 'flutter-prep-2f8a0.firebasestorage.app',
    measurementId: 'G-0ZJJWEQ7KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTbl3jxUldCS-BH9pXj7ME5ZoSGtVR-E',
    appId: '1:726365459693:android:91992acd2a71c3de19e8e4',
    messagingSenderId: '726365459693',
    projectId: 'flutter-prep-2f8a0',
    storageBucket: 'flutter-prep-2f8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHpFrbV_0BL5-zcbs4JQhwnK1B3TZyApw',
    appId: '1:726365459693:ios:2a16834bdd57cf9a19e8e4',
    messagingSenderId: '726365459693',
    projectId: 'flutter-prep-2f8a0',
    storageBucket: 'flutter-prep-2f8a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHpFrbV_0BL5-zcbs4JQhwnK1B3TZyApw',
    appId: '1:726365459693:ios:2a16834bdd57cf9a19e8e4',
    messagingSenderId: '726365459693',
    projectId: 'flutter-prep-2f8a0',
    storageBucket: 'flutter-prep-2f8a0.firebasestorage.app',
    iosBundleId: 'com.example.flutterPrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJGPLdIRHq9fOu64zSiHf3TAwoCimVTgw',
    appId: '1:726365459693:web:d3a40439b3e97bba19e8e4',
    messagingSenderId: '726365459693',
    projectId: 'flutter-prep-2f8a0',
    authDomain: 'flutter-prep-2f8a0.firebaseapp.com',
    storageBucket: 'flutter-prep-2f8a0.firebasestorage.app',
    measurementId: 'G-WNPSP4E158',
  );
}
